sudo: required
services:
  - docker

before_install:
  - docker build -t michjop/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run michjop/react-test npm test -- --coverage

after_success:
  - docker build -t michjop/multi-client ./client
  - docker build -t michjop/multi-nginx ./nginx
  - docker build -t michjop/multi-server ./server
  - docker build -t michjop/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push michjop/multi-client
  - docker push michjop/multi-nginx
  - docker push michjop/multi-server
  - docker push michjop/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-462135668015
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY 

